CUDA_VISIBLE_DEVICES=6 python3 train_tuning.py --model resnet18 --dataset CIFAR100_cutout --val_rat 0.0 --dls_act sech  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 1.5 --dls_coe1 0.15  --momentum 0.0 --lr 0.5 --rep_num 1 > tmp.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 python3 train_tuning.py --model resnet18 --dataset CIFAR100_cutout --val_rat 0.0 --dls_act sech  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 1.5 --dls_coe1 0.5  --momentum 0.0 --lr 0.5 --rep_num 1 > tmp.txt 2>&1 &
CUDA_VISIBLE_DEVICES=0 python3 train_tuning.py --model resnet18 --dataset CIFAR100_cutout --val_rat 0.0 --dls_act sech  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 1.5 --dls_coe1 0.3  --momentum 0.0 --lr 0.5 --rep_num 1 > tmp.txt 2>&1 &
#CUDA_VISIBLE_DEVICES=2 python3 train_tuning.py --model resnet50 --dataset CIFAR100_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15  --momentum 0.0 --lr 0.5 > tmp.txt 2>&1 &

# CUDA_VISIBLE_DEVICES=0 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 1 > C10_tuning_cyclic0.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=1 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 2 > C10_tuning_cyclic1.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=2 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 3 > C10_tuning_cyclic2.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=3 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 4 > C10_tuning_cyclic3.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=4 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 5 > C10_tuning_cyclic4.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=5 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 6 > C10_tuning_cyclic5.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=6 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 7 > C10_tuning_cyclic6.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=7 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 8 > C10_tuning_cyclic7.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=8 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 9 > C10_tuning_cyclic8.txt 2>&1 &
# CUDA_VISIBLE_DEVICES=9 python3 train_tuning.py --model resnet18 --dataset CIFAR10_cutout --val_rat 0.0 --dls_act sech --norm_loss  --setting cyclic_dls_singlerun --seed 42 --dls_coe0 2.5 --dls_coe1 0.15 --rep_num 10 > C10_tuning_cyclic9.txt 2>&1
CUDA_VISIBLE_DEVICES=7 python3 train_tuning.py --model resnet18 --dataset CIFAR100_cutout --val_rat 0.0 --setting baseline_singlerun --seed 42 --dls_coe0 1.5 --dls_coe1 0.5 --epochs 2 > tmp.txt 2>&1 &